### ISSUE TITLE
Portland Scraper fails to parse event

### ISSUE THREAD

**Issue by JacksonMaxfield** [CouncilDataProject/cdp-scrapers#86]
See log: https://github.com/CouncilDataProject/portland/runs/5981645393?check_suite_focus=true

Seems like we just need to be safer about what page content is expected:
```python
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.9.12/x64/lib/python3.9/site-packages/cdp_backend/bin/run_cdp_event_gather.py", line 90, in main
    flow = pipeline.create_event_gather_flow(
  File "/opt/hostedtoolcache/Python/3.9.12/x64/lib/python3.9/site-packages/cdp_backend/pipeline/event_gather_pipeline.py", line 117, in create_event_gather_flow
    events = get_events_func(
  File "/opt/hostedtoolcache/Python/3.9.12/x64/lib/python3.9/site-packages/cdp_portland_backend/scraper.py", line 18, in get_events
    return get_portland_events(from_dt=from_dt, to_dt=to_dt, **kwargs)
  File "/opt/hostedtoolcache/Python/3.9.12/x64/lib/python3.9/site-packages/cdp_scrapers/instances/portland.py", line 771, in get_portland_events
    return scraper.get_events(begin=from_dt, end=to_dt, **kwargs)
  File "/opt/hostedtoolcache/Python/3.9.12/x64/lib/python3.9/site-packages/cdp_scrapers/instances/portland.py", line 732, in get_events
    [
  File "/opt/hostedtoolcache/Python/3.9.12/x64/lib/python3.9/site-packages/cdp_scrapers/instances/portland.py", line 733, in <listcomp>
    self.get_event(begin + timedelta(days=day))
  File "/opt/hostedtoolcache/Python/3.9.12/x64/lib/python3.9/site-packages/cdp_scrapers/instances/portland.py", line 691, in get_event
    agenda_uri=self.get_agenda_uri(event_page.soup),
  File "/opt/hostedtoolcache/Python/3.9.12/x64/lib/python3.9/site-packages/cdp_scrapers/instances/portland.py", line 658, in get_agenda_uri
    agenda_uri_element = parent_agenda_uri_element.find("a")
AttributeError: 'NoneType' object has no attribute 'find'
```

cc @Shak2000

**Comment by JacksonMaxfield** [comment]
Note to self:

Need to reprocess events:
* 2021-08-19 - 2021-08-31

**Comment by Shak2000** [comment]
Hi Jackson. I would like to be assigned this issue.

**Comment by Shak2000** [comment]
I looked at the Portland city government website and the Portland scraper, and I found out that the only agenda from August 19 to August 31 was [a cancelled meeting on August 25-26](https://www.portland.gov/council/agenda/2021/8/25). If the council meeting is cancelled, should I return an empty event, or should we return `None`?
